### PR TITLE
Create JavaScript.Web.Storage module

### PR DESCRIPTION
**Pull request by tysonzero**
This should match the behavior of JavaScript.Web.Storage from ghcjs-base.

### CODE REVIEW

**Comment by tysonzero** [comment]
This address issue #2

**Comment by louispan** [comment]
Thank you. I'll merge this and upload a new hackage version

**Comment by tysonzero** [comment]
Thank you, fantastic!!

**Comment by louispan** [comment]
https://hackage.haskell.org/package/ghcjs-base-stub-0.1.0.3 is on hackage

**Comment by tysonzero** [comment]
Awesome, thanks!

**Pull request merged**
